### PR TITLE
Support ansible-core>=2.16.0

### PR DESCRIPTION
**Pull request by jovial**
See: https://github.com/ansible/ansible/commit/8db9bd757444fba6dd23fcb067e261d877926a33

### CODE REVIEW

**Comment by jovial** [comment]
Notice possible issue with tags. Will investigate further.

**Comment by jovial** [comment]
The issue I was seeing was:
```
(ansible-2.15) vagrant@controller0:/vagrant$ ansible-playbook ansible/test.yml -t configdrive,distribution
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] **********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [include_role : jriguera.configdrive] ********************************************************************************************************************************************************************************************
[DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks instead. See https://docs.ansible.com/ansible-core/2.15/user_guide/playbooks_reuse_includes.html for details. This feature will be removed in version 
2.16. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

TASK [jriguera.configdrive : Install required packages to create the images] **********************************************************************************************************************************************************
[WARNING]: Skipping plugin (/vagrant/ansible/filter_plugins/networkd.py), cannot load: No module named 'kayobe'
[WARNING]: Skipping plugin (/vagrant/ansible/filter_plugins/networks.py), cannot load: No module named 'kayobe'
ok: [localhost] => (item={'key': 'genisoimage', 'value': {'state': 'latest'}})
ok: [localhost] => (item={'key': 'gzip', 'value': {'state': 'latest'}})
ok: [localhost] => (item={'key': 'coreutils', 'value': {'state': 'latest'}})

TASK [jriguera.configdrive : Include OS specific variables] ***************************************************************************************************************************************************************************
ok: [localhost]

TASK [jriguera.configdrive : Create configdrive temporary metadata folder] ************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'configdrive_instance_dir' is undefined. 'configdrive_instance_dir' is undefined\n\nThe error appears to be in '/vagrant/ansible/roles/jriguera.configdrive/tasks/configdrive.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create configdrive temporary metadata folder\n  ^ here\n"}
```
But this is reproducible with the old include too. Sample playbook to reproduce:

```
- hosts: localhost
  tasks:
    - include_role:
        name: jriguera.configdrive
      tags: always
      vars:
        configdrive_os_family: "Debian"
        configdrive_uuid: "uuid-test-01"
        configdrive_fqdn: "test.example.com"
        configdrive_name: "test"
        configdrive_ssh_public_key: "my ssh key"
        configdrive_config_dir: "/tmp/configdrive/"
        configdrive_volume_path: "/tmp/configdrive/"
        configdrive_resolv:
          domain: "example.com"
          search: "hola.example.com"
          dns: ['8.8.8.8']
        configdrive_hosts:
          - ['127.0.1.1', 'host1.domain.com']
          - ['127.0.1.2', 'host3.domain.com']
        configdrive_network_device_list:
          - device: "eth1"
            bootproto: "dhcp"
          - device: "eth2"
            bootproto: "dhcp"
            type: "phy"
          - device: "eth0.500"
            type: "vlan"
            address: "10.1.1.10"
            netmask: "255.255.255.0"
            gateway: "10.1.1.1"
            nameservers: 
              - 8.8.8.8
              - 9.9.9.9
            domain: "hola.com"
            backend: ["eth0"]

```
It works as expected with import_role instead.

**Comment by jovial** [comment]
This seems consistent with the old behaviour of include. For instance if I add a fail task to configdrive.yml it will still execute with:

ansible-playbook ansible/test2.yml -t configdrive,distribution

with include_tasks this would be skipped.

**Review by markgoddard — APPROVED** [review]

**Comment by markgoddard** [comment]
The old include is more similar to import_tasks than include_tasks.

**Comment by jriguera** [comment]
Hey guys, Unfortunately I cannot properly test the changes, but they look good to me

**Comment by markgoddard** [comment]
Thanks @jriguera, are you able to merge the change?

**Comment by jriguera** [comment]
Done.
Sorry for the delay,  Ive got distracted.

**Comment by markgoddard** [comment]
Thanks!

**Pull request merged**
