### PR TITLE
Fix network_info.json Jinja syntax

### PR DESCRIPTION
**Pull request by markgoddard**
Included an unnecessary endif.

### CODE REVIEW

**Comment by markgoddard** [comment]
Sorry, messed up a copy/paste while transferring the fix to my local repo...

**Comment by markgoddard** [comment]
@jriguera ping :)

**Comment by jriguera** [comment]
Having a look!

**Comment by jriguera** [comment]
Thanks!
Merged!

**Comment by markgoddard** [comment]
Awesome, thanks

**Pull request merged**
